[phases.setup]
nixPkgs = ["php", "composer", "nginx", "php81Extensions", "sqlite"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan migrate --force",
    "php artisan config:clear",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
